### ISSUE TITLE
[BUG] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [deltazefiro/Amarok-Hider#160]
xposed lib is not available in a [trusted maven repo](https://gitlab.com/fdroid/fdroidserver/-/blob/df97ebe05298b6c0261d2dfbc1c2dd05687cfc7c/fdroidserver/scanner.py#L456-L479)

```
> Task :app:processFossReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processFossReleaseResources'.
> Could not resolve all files for configuration ':app:fossReleaseCompileClasspath'.
   > Could not find de.robv.android.xposed:api:82.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/de/robv/android/xposed/api/82/api-82.pom
       - https://repo.maven.apache.org/maven2/de/robv/android/xposed/api/82/api-82.pom
       - https://jitpack.io/de/robv/android/xposed/api/82/api-82.pom
     Required by:
         project :app
```

ref: https://github.com/deltazefiro/Amarok-Hider/commit/e1d1f1e43997eec7b712a2e8c92cd841942baf67

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/3682805926959d87c6d530d3dd4eeb32f67b6aa8

**Comment by deltazefiro** [comment]
Hi @licaon-kter
I imported the Xposed library from the official Xposed API repository at `https://api.xposed.info/`. I believe it's a common requirement for every exposed module. Any suggestions for removing it?

**Comment by licaon-kter** [comment]
Maybe we can build it from source? Since this is a repro app... I guess you might need to build it too :( :)

**Comment by deltazefiro** [comment]
@licaon-kter 
Well, I found that the Xposed library can also be obtained from jcenter, although it is deprecated. 
I will create a new release without `https://api.xposed.info/` :D

**Comment by licaon-kter** [comment]
That fixes it https://gitlab.com/fdroid/fdroiddata/-/commit/8cfa2753b36958f04ddf6fe6fc75ebf7677dc04d

>  jcenter, although it is deprecated

good luck to _future you_ when the times comes and those are unreachable :shrug:

**Comment by deltazefiro** [comment]
> good luck to future you when the time comes and that is unreachable 🤷

☹️ There's another solution: we can include the .jar library in the source tree. 
However, as per F-Droid Inclusion Policy:

> Binary dependencies such as JAR files have to be built from source or installed from Debian repos.

I'm not sure if I can do this. I found that [Scoop](https://github.com/TacoTheDank/Scoop/tree/main/app/libs) did so and got included in F-Droid, so I believe it's OK, right?

**Comment by licaon-kter** [comment]
Not true, those are not used: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/taco.scoop.yml#L87

But https://github.com/TacoTheDank/Scoop/blob/v2.4.2/build.gradle#L9

**Comment by ThreeDeeJay** [comment]
Yeah, looks like the Xposed API was removed from official repositories.
Luckily I found a mirror (not sure how trustworthy it is, though, perhaps someone could compare the hashes?):
https://github.com/ThreeDeeJay/DarQ/blob/3231ce1f0962f9d57596499319560f6e942c5232/build.gradle#L22

[This archive](https://web.archive.org/web/20240907130722/https://archiva.interlocsolutions.com/archiva/repository/internal/de/robv/android/xposed/api/82/) might work if that repo ever goes under (unless Internet Archive beats it to the punch given recent events)
```
maven { url "https://web.archive.org/web/20240907130748/https://archiva.interlocsolutions.com/archiva/repository/internal" }

```

Like, seriously, how come nobody ever though of archiving [this](https://web.archive.org/web/*/https://dl.google.com/dl/android/maven2/de/robv/android/xposed/**)?
```
https://dl.google.com/dl/android/maven2/de/robv/android/xposed/api/82/api-82.pom
```

**Comment by licaon-kter** [comment]
Jcenter was finally turned off, yes...

**Comment by deltazefiro** [comment]
Hey @licaon-kter 
I noticed that [Tarnhelm](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16774/diffs?commit_id=a2f7e95725df5b89148e6e735d92f41cf1a60b3e) appears to address this issue in some way. However, I don't fully understand how it achieves this. Could you please provide some insight?

**Comment by licaon-kter** [comment]
it builds it before building the app:
```
...
    sudo:
      - echo "deb http://deb.debian.org/debian sid main" > /etc/apt/sources.list.d/sid.list
      - apt-get update
      - apt-get install -y -t sid openjdk-8-jdk-headless
    srclibs:
      - XposedBridge@v82
    prebuild:
      - sed -i -e '/versionCode/s/date.*/$$VERCODE$$/' -e "s|'de.robv.android.xposed:api:82'|files('libs/api.jar')|"
        build.gradle
      - sed -i -e 's/api.xposed.info/maven.google.com/' ../settings.gradle
      - cd $$XposedBridge$$
      - sed -i -e 's/1.5.0/3.3.3/' -e '/repositories {/a google()' -e 's/jcenter/mavenCentral/g'
        build.gradle
      - sed -i -e 's/2.10/4.10.1/' gradle/wrapper/gradle-wrapper.properties
      - sed -i -e '/sdkSources/d' -e 's/hiddenapi.assembleRelease/":hiddenapistubs:assembleRelease"/'
        app/build.gradle
    build:
      - pushd $$XposedBridge$$
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 gradle :app:generateAPI
      - popd
      - mkdir -p libs
      - mv $$XposedBridge$$/app/build/api/api.jar libs
```

then puts the jar in the proper place for gradle to pick it up when building the app

but, your app is build reproducible (Tarnhelm is not) so for you, our built jar needs to be reproducible too, so it means that you need to build the lib as well
